<template><div class="source-page"><section class="row featured-top cropped-feature"><div class="featured-background capabilities"><img src="/images/service-1.jpg.jpeg" alt=""></div><div class="photo-gradient"></div><div class="container featured-container"><div class="row"><div class="col-md-6 featured-content"><h1 class="featured-section">Services</h1><h2 class="featured-title">Collaborative legal talent</h2><div class="featured-details"><p><span class="text-head-blue">Working side-by-side with clients, our results-oriented, collaborative approach has made Kohlerackels the firm of choice for many.</span> With experience in over 100 practice areas, our attorneys and business professionals advocate for clients and offer practical solutions to challenging business problems.</p></div></div></div></div></section><section class="full-width-blue people-search"><div class="container"><h1>Services</h1><div class="service-columns"><div v-for="group in groups" :key="group" class="service-group"><button type="button" @click="toggle(group)">{{group}}<span>{{open[group]?'-':'+'}}</span></button><div v-if="open[group]" class="service-list"><a href="#">Corporate</a><a href="#">Litigation</a><a href="#">Employment</a><a href="#">Intellectual Property</a></div></div></div></div></section></div></template>

<style scoped>.featured-content{padding-top:40px;padding-bottom:40px}.featured-section{color:#b7801d}.featured-title{font-size:48px;line-height:1.05}.full-width-blue{padding:45px 0;background:#0d4b80;color:#fff}.service-columns{max-width:900px}.service-group{border-bottom:1px solid rgba(255,255,255,.35)}.service-group>button{width:100%;display:flex;justify-content:space-between;text-align:left;padding:15px 0;border:0;background:transparent;color:#fff;font-size:19px}.service-list{display:grid;grid-template-columns:repeat(2,1fr);gap:8px 30px;padding:0 0 18px}.service-list a{color:#fff;text-decoration:none}@media(max-width:575px){.service-list{grid-template-columns:1fr}}</style>

<script setup>
import { reactive } from 'vue'
const groups=['Corporate','Litigation','Labor & Employment','Intellectual Property']
const open=reactive({})
const toggle=group=>{open[group]=!open[group]}
</script>